export const config = {
  appName: 'Idle Night',
  tickTime: 100,
  playerAutoAttackEvery: 1000,
  enemyAutoAttackEvery: 1100,
  attackDuration: 150,
  damageDuration: 500,
  defaultHealthColor: 'green',
  defaultManaColor: 'blue',
  startWood: 30,
  startRocks: 30,
  startGold: 300,
  viewportWidth: 26,
  viewportHeight: 22,
  minViewportWidth: 14,
  minViewportHeight: 10,
  iconWidth: 16,
  iconHeight: 16,
  startPositionX: 108,
  startPositionY: 128,
};
